### ISSUE TITLE
Copy  required_def    Command to display success  But there are no display tags 

### ISSUE THREAD

**Issue by q848899** [soler91/HH-Firewall-Markers#1]
Copy  required_def    Command to display success  But there are no display tags why? twserver

**Comment by soler91** [comment]
You probably moved the folder when you are supposed to move the 2 files that are inside the folder.

**Comment by q848899** [comment]
No, and I have 2 folder all  copy file   but still  No sign can be seen

**Comment by q848899** [comment]
OK, it's repaired, thanks
