### ISSUE TITLE
No longer works after Nov 30th patc

### ISSUE THREAD

**Issue by terarian** [soler91/HH-Firewall-Markers#8]
any plan to update it? TY in advance.

**Comment by soler91** [comment]
It still works, you only need to map the opcodes

**Comment by Yasukii** [comment]
I dont think its working. 
since im getting these error , i have all the opcodes tho-
ty if you could help.



![hhsigns](https://user-images.githubusercontent.com/34219032/33529444-438ad4fc-d871-11e7-9419-5ae7d0d60366.png)

**Comment by soler91** [comment]
If you have the opcodes, tell me what is S_SPAWN_BUILD_OBJECT opcode

**Comment by Yasukii** [comment]
For me S_SPAWN_BUILD_OPJECT = 29251

**Comment by soler91** [comment]
Alright so, if u copied that from your map you got a typo, if you didnt did you check that you put it on the right protocol version (protocol.323308.map)? because literally what the screenshot says is the opcode is not there

**Comment by Yasukii** [comment]
![map](https://user-images.githubusercontent.com/34219032/33529554-ad799ca8-d872-11e7-8668-062e990b9643.png)

i dont find a typo and its the right protocol :/

**Comment by Yasukii** [comment]
no im stupid

**Comment by soler91** [comment]
yours says OPJECT with a P it should be a :b:  :ok_hand:

**Comment by Yasukii** [comment]
yes i noticed
rip me 
ty for the help tho , appreciate it

**Comment by Owyn** [comment]
> It still works, you only need to map the opcodes

except there is no way to do that? 

Maybe it's time to replace signs with other items
